### PR TITLE
Updated table of content in acdademic UG

### PR DESCRIPTION
**Pull request by luziyi9898**

### CODE REVIEW

**Comment by farice9** [comment]
Can you add > for "warning" and "useful information" before we merge this PR

**Comment by luziyi9898** [comment]
> Can you add > for "warning" and "useful information" before we merge this PR

Adding now

**Comment by luziyi9898** [comment]
> Can you add > for "warning" and "useful information" before we merge this PR

The formatting has been updated!

**Review by farice9 — APPROVED** [review]
LGTM quick response. 5/7.

**Pull request merged**
